NAME			=	libft.a
NAME_DEBUG		=	libft_debug.a
INCS			=	libft.h
SRCS			=	ft_memset.c ft_bzero.c ft_memcpy.c ft_memmove.c ft_memchr.c ft_memcmp.c ft_memccpy.c \
					ft_strlen.c ft_strlcpy.c ft_strlcat.c ft_strchr.c ft_strrchr.c ft_strnstr.c \
					ft_strncmp.c ft_atoi.c ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c \
					ft_isprint.c ft_toupper.c ft_tolower.c ft_calloc.c ft_strdup.c \
					ft_substr.c ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c \
					ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c \
					ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c \
					ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c ft_gnl.c ft_utoa.c ft_uitoa.c \
					ft_isnum.c ft_strcmp.c ft_strnrcmp.c ft_atol.c ft_memfree.c ft_numlen.c ft_is_all_num.c

OBJS			=	$(patsubst %.c, %.o, $(SRCS))

SRCS_DIR		=	srcs/
OBJS_DIR		=	objs/
INCS_DIR		=	includes/

SRCS_FILE		=	$(addprefix $(SRCS_DIR), $(SRCS))
OBJS_FILE		=	$(addprefix $(OBJS_DIR), $(OBJS))
INCS_FILE		= 	$(addprefix $(INCS_DIR), $(INCS))

CC				=	gcc
AR				=	ar rcs
RM				=	rm -rf
CFLAGS			=	-Wall -Wextra -Werror
HEADER_FLAG		=	-I$(INCS_DIR)

all:			$(NAME)

$(NAME):		$(OBJS_DIR) $(OBJS_FILE)
				@$(AR) libft.a $(OBJS_FILE)

$(OBJS_DIR) :
					@mkdir -p $(OBJS_DIR)	

$(OBJS_DIR)%.o :	$(SRCS_DIR)%.c 
					$(CC) -c $(CFLAGS) $(HEADER_FLAG) $< -o $@

clean:
				@$(RM) $(OBJS_FILE)

fclean:	
				@$(RM) $(NAME_DEBUG) $(NAME) $(OBJS_DIR)

re:				fclean $(NAME)

.PHONY:			all clean fclean re
